package entities;
// Generated Sep 12, 2012 4:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * StaffPermissionId generated by hbm2java
 */
public class StaffPermissionId  implements java.io.Serializable {


     private int permissionid;
     private String staffid;

    public StaffPermissionId() {
    }

    public StaffPermissionId(int permissionid, String staffid) {
       this.permissionid = permissionid;
       this.staffid = staffid;
    }
   
    public int getPermissionid() {
        return this.permissionid;
    }
    
    public void setPermissionid(int permissionid) {
        this.permissionid = permissionid;
    }
    public String getStaffid() {
        return this.staffid;
    }
    
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StaffPermissionId) ) return false;
		 StaffPermissionId castOther = ( StaffPermissionId ) other; 
         
		 return (this.getPermissionid()==castOther.getPermissionid())
 && ( (this.getStaffid()==castOther.getStaffid()) || ( this.getStaffid()!=null && castOther.getStaffid()!=null && this.getStaffid().equals(castOther.getStaffid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPermissionid();
         result = 37 * result + ( getStaffid() == null ? 0 : this.getStaffid().hashCode() );
         return result;
   }   


}


