package entities;
// Generated Sep 12, 2012 4:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * StaffPermission generated by hbm2java
 */
public class StaffPermission  implements java.io.Serializable {


     private StaffPermissionId id;

    public StaffPermission() {
    }

    public StaffPermission(StaffPermissionId id) {
       this.id = id;
    }
   
    public StaffPermissionId getId() {
        return this.id;
    }
    
    public void setId(StaffPermissionId id) {
        this.id = id;
    }




}


